import Main from "./componentes/main"
import Header from "./componentes/Header"
import Footer from "./componentes/Footer"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">

      <Header />
      <Main />
      <Footer />

      <body>{children}</body>
    </html>
  )
}
